apiVersion: apps/v1
kind: Deployment
metadata:
  name: isthisart-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: isthisart-app
  template:
    metadata:
      labels:
        app: isthisart-app
    spec:
      containers:
        - name: isthisart-app
          image: 8sem/isthisart-app:latest # Replace with your Docker Hub image
          ports:
            - containerPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: isthisart-app-service
spec:
  type: NodePort
  selector:
    app: isthisart-app
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
