name: CI/CD for isthisart-app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/isthisart-app:latest

  deploy:
    needs: build
    runs-on: [self-hosted, Windows, X64] # Deploys on local machine with Minikube

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status

      # ✅ Added step — align Docker with Minikube context (Windows PowerShell syntax)
      - name: Configure Docker to use Minikube context
        shell: powershell
        run: |
          & minikube -p minikube docker-env --shell powershell | Invoke-Expression
          docker context use default

      # ✅ Added step — load your image inside Minikube’s Docker
      - name: Load Docker Image into Minikube
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/isthisart-app:latest
          minikube image load ${{ secrets.DOCKER_USERNAME }}/isthisart-app:latest

      - name: Deploy to Minikube using k8s.yml
        run: |
          kubectl apply -f k8s/k8s.yml
          kubectl get pods -o wide

      - name: Expose isthisart-app Service
        run: |
          kubectl get svc
          minikube service list

      - name: Get Minikube Service URL
        run: |
          minikube service isthisart-app-service --url
